baseURL = 'http://erinpark.org/'
languageCode = 'en-us'
title = "Erin Park's Portfolio"
theme = "archie"
copyright = "© Erin Park"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Portfolio & Resume Site"
# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/sky-larke"


# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
